(ns org.healthsciencessc.rpms2.consent-admin.process.init
  (:require [org.healthsciencessc.rpms2.consent-admin.process.groups]
            [org.healthsciencessc.rpms2.consent-admin.process.language]
            [org.healthsciencessc.rpms2.consent-admin.process.locations]
            [org.healthsciencessc.rpms2.consent-admin.process.login]
            [org.healthsciencessc.rpms2.consent-admin.process.organizations]
            [org.healthsciencessc.rpms2.consent-admin.process.protocol]
            [org.healthsciencessc.rpms2.consent-admin.process.protocol-version]
            [org.healthsciencessc.rpms2.consent-admin.process.endorsement-type]
            [org.healthsciencessc.rpms2.consent-admin.process.endorsement]
            [org.healthsciencessc.rpms2.consent-admin.process.meta-item]
            [org.healthsciencessc.rpms2.consent-admin.process.policy]
            [org.healthsciencessc.rpms2.consent-admin.process.policy-definition]
            [org.healthsciencessc.rpms2.consent-admin.process.roles]
            [org.healthsciencessc.rpms2.consent-admin.process.users]))