(ns org.healthsciencessc.consent.services.process.init
  (:require [org.healthsciencessc.consent.services.process.consent]
            [org.healthsciencessc.consent.services.process.encounter]
            [org.healthsciencessc.consent.services.process.endorsement]
            [org.healthsciencessc.consent.services.process.endorsement-type]
            [org.healthsciencessc.consent.services.process.group-role]
            [org.healthsciencessc.consent.services.process.group]
            [org.healthsciencessc.consent.services.process.language]
            [org.healthsciencessc.consent.services.process.location]
            [org.healthsciencessc.consent.services.process.meta-item]
            [org.healthsciencessc.consent.services.process.organization]
            [org.healthsciencessc.consent.services.process.policy-definition]
            [org.healthsciencessc.consent.services.process.policy]
            [org.healthsciencessc.consent.services.process.protocol]
            [org.healthsciencessc.consent.services.process.protocol-version]
            [org.healthsciencessc.consent.services.process.protocol-version-published]
            [org.healthsciencessc.consent.services.process.protocol-version-export]
            [org.healthsciencessc.consent.services.process.role]
            [org.healthsciencessc.consent.services.process.role-mapping]
            [org.healthsciencessc.consent.services.process.text-i18n]
            [org.healthsciencessc.consent.services.process.user-group]
            [org.healthsciencessc.consent.services.process.user]
            [org.healthsciencessc.consent.services.process.user-role]
            [org.healthsciencessc.consent.services.process.widget]))

